export const queryKeys = {
  status: ["status"] as const,
  downloads: ["downloads"] as const,
  uploadClients: ["clients", "uploads"] as const,
  clients: (filter: string) => ["clients", filter] as const,
  client: (ecid: number) => ["client", ecid] as const,
  clientBrowse: (ecid: number) => ["client-browse", ecid] as const,
  servers: ["servers"] as const,
  categories: ["categories"] as const,
  sharedFiles: ["shared-files"] as const,
  sharedFile: (hash: string) => ["shared-file", hash] as const,
  sharedDirectories: ["shared-directories"] as const,
  kad: ["kad"] as const,
  amuleLogs: ["logs", "amule"] as const,
  amuleLog: (tail: number) => ["logs", "amule", tail] as const,
  serverInfoLogs: ["logs", "serverinfo"] as const,
  serverInfoLog: (tail: number) => ["logs", "serverinfo", tail] as const,
  statisticsTree: ["statistics", "tree"] as const,
  statisticsGraph: (graph: string, width: number) => ["statistics", "graph", graph, width] as const,
  preferences: ["preferences"] as const,
  passwordStatus: ["auth", "password-status"] as const,
  searches: ["searches"] as const,
  searchResults: (searchId: number | undefined) => ["search-results", searchId] as const,
  download: (hash: string) => ["download", hash] as const,
  downloadFilenames: (hash: string) => ["download-filenames", hash] as const,
  downloadComments: (hash: string) => ["download-comments", hash] as const,
  downloadA4af: (hash: string) => ["download-a4af", hash] as const,
} as const;
